// config_mousekey.h
#pragma once

#if defined(MOUSEKEY_ENABLE)

#define MOUSEKEY_DELAY 1
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_TIME_TO_MAX 100 
#define MOUSEKEY_WHEEL_DELAY 1
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 12
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#endif