#pragma once

#define VIAL_KEYBOARD_UID \
    { 0x73, 0xFD, 0x11, 0x1F, 0x7F, 0x19, 0xC9, 0x33 }

#define VIAL_UNLOCK_COMBO_ROWS \
    { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS \
    { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define SPLIT_TRANSPORT_MIRROR

#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_MAX_SPEED 12

#define RGB_MATRIX_DEFAULT_HUE 55