/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID \
    { 0x73, 0xFD, 0x11, 0x1F, 0x7F, 0x19, 0xC9, 0x33 }

#define VIAL_UNLOCK_COMBO_ROWS \
    { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS \
    { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 12

#define EE_HANDS
#define SPLIT_TRANSPORT_MIRROR

// #define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_DELTA 1
#define MOUSEKEY_WHEEL_MAX_SPEED 12
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#define SPLIT_POINTING_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define CIRQUE_PINNACLE_ADDR 0x2A
// #define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X
#define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_INVERT_Y
// #define POINTING_DEVICE_ROTATION_180

#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_TAPPING_TERM 200

// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE

#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 12
#define AUTO_MOUSE_TIME 200
